### PR TITLE
1.16.4

### PR DESCRIPTION
**Pull request by CorgiTaco**
Alright only major changes I had to make are in your match item(same as vanilla 1.16.4), using the "BiomeLoadingEvent" which allows your feature to affect datapack biomes, registered your torch feature(configured aswell) which is required by 1.16, added your license project to mods.toml(required by forge), and I added a minor optimization in the feature generation which *should* save on ram and should be overall faster. Lmk if you need any changes and ofc, make sure to test it on your own and verify it works :D

### CODE REVIEW

**Comment by CorgiTaco** [comment]
Alright turns out the wall torch texture is uhhhhh busted. Lemme see what i can do about that

**Comment by CorgiTaco** [comment]
alrighty this isnt gonna be as easy as i thought lol

**Comment by CorgiTaco** [comment]
Alright we should be good!

**Comment by MattCzyr** [comment]
Looks good, thanks!

**Pull request merged**
